### ISSUE TITLE
Could it be no iframe?

### ISSUE THREAD

**Issue by lyscop** [tabfloater/tabfloater#234]
I find there is the title bar in the top, can it be hide, and when the mouse move up, it show, and except stroll, press down left button, and move the mouse, the window can be followed to move?

**Comment by ba32107** [comment]
Hi, sadly this is not possible. On Windows, Chrome draws its own title bar, it's not possible to remove it programmatically. It is possible on Linux though.

However, tracking mouse movements and reacting to them is not possible via browser extensions.
