### ISSUE TITLE
It does not stay on top

### ISSUE THREAD

**Issue by denzo** [tabfloater/tabfloater#247]
It is advertised as:
```Always on top
The floating tab always keeps on top, so you can interact with other websites.```

Once I interact with a non floating window, it goes on top of the float.

**Comment by ba32107** [comment]
Hi, what operating system and browser you use?

**Comment by Giiiiili** [comment]
> Hi, what operating system and browser you use?

+1🙋‍
Windows 10 & Google Chrome

**Comment by ba32107** [comment]
Few things to check:
 - Did you [download and install the companion](https://www.tabfloater.io/download)?
 - When you float a tab, does the icon have a red `!`? If you hover over it, what happens?
 - Can you enable debugging in the options, try the float again, and paste the logs from the log file here?

**Comment by ba32107** [comment]
@denzo, @Giiiiili, can you try the above suggested steps?

**Comment by ba32107** [comment]
Closing this - please comment if you still have problems.

**Comment by Giiiiili** [comment]
> @denzo, @Giiiiili, can you try the above suggested steps?

thx! it's really helpful
