### ISSUE TITLE
Option to remember floating window position + size

### ISSUE THREAD

**Issue by kostasvl** [tabfloater/tabfloater#252]
Hi. Thanks for this great extension. It's almost ideal for me - see below ;)

## Summary
I would really appreciate it if the floating window would have the option to simply remember its previous size and position.

## Use case
I like the clever attempts to automatically position that window, but for me (an ultrawide screen user), I would just prefer it if it would simply always go to the bottom right corner, with the specific dimensions and position I will specify the first time.

The current "Fixed Position" option, when set to Bottom Right, always make the floating too small/narrow for me. I have to resize it every time.

Hopefully, what I'm asking is the Dumb Positioning option :), and therefore relatively easier to do than the existing options.

-----
By the way, I tried the Smart Positioning option, and it doesn't seem to work for me. It looks like nothing happens most of the time, although sometimes the tab will be moved to a new (random?) position in Chrome's tab bar. No floating window is ever created. Want me to create a new issue with more details?

Thanks!

**Comment by ba32107** [comment]
Hi @kostasvl, sure, this should be doable. We could add a "Custom" tab size setting, as well as viewport offsets not only for the top side, but all 4 sides. That would allow you to fully specify the dimensions and location of the tab.

This should not be a huge thing, however I do not have much free time these days. I will get on it as soon as I can. Feel free to remind me here if I take too long!

As for the Smart Positioning, this definitely doesn't sound right. The floating window should appear as normal. Please do open a separate issue for it, and we can discuss it there. 

And thanks for the donation :) It means a lot!

**Comment by kostasvl** [comment]
I have no expectations whatsoever. The donation was for the work you already released! The above request was just: "if you are ever in the mood to look at the code again, please consider this (hopefully simple) idea too". Enjoy the summer my friend - that's a higher priority :).

**Comment by kostasvl** [comment]
By the way, Smart Positioning started working, somehow. Maybe it was the fact I first tested it with its two suboptions also ticked, and I have since tried with and without. I don't know. After it started working, I can't make it repro again. Oh well.

**Comment by ba32107** [comment]
This is code complete, I will release it soon, just want to add one more issue to the next version.

**Comment by kostasvl** [comment]
Got the update. It works great! Thanks! 👍

**Comment by ba32107** [comment]
Excellent. Glad to hear :) It was a great, simple idea, so thank you!
