### ISSUE TITLE
Option to automatically maximize the youtube player within the floating window

### ISSUE THREAD

**Issue by kostasvl** [tabfloater/tabfloater#253]
## Summary
This extension would be even more amazing if it could (optionally) automatically maximize the youtube video player within the floating window.

## Use case
~70% of the time I use this extension (or similar ones, including Chrome's PiP) is to watch long youtube videos in the background. I suspect I'm not alone in this.

## Proposed solution
Using the Tab Floater, this isn't currently possible, even manually. I had to download another extension called "Windowed - floating Youtube/every website" (https://github.com/dralletje/Windowed), which changes what youtube's maximize button does, to allow maximizing the player within the current window. Hopefully this is a feature Google exposes in the player's public API, but I'm no web dev. Alternatively, that extension is also open source, so perhaps "inspiration" could be found there :P.

I guess you would only implement this for youtube.com urls, for simplicity. Embedded videos would be a bonus, but they are easy enough to open on youtube.com first.

Thanks. No pressure whatsoever - goes without saying! I really appreciate what you've given us already, and I wouldn't be surprised if you are sick of having to fight Google and their constant changes ;)

**Comment by ba32107** [comment]
Well, actually the reason why I started working on TabFloater is that all the other extensions available were _only_ focused on video use-cases. So TabFloater is supposed to be a solution just for normal websites.

That being said, I do see the value in not having to install multiple extensions for this, if one needs both video PiP and TabFloater's functionality. I'll keep this one on the backburner and will have a look once I have some time to work on it :)

**Comment by ba32107** [comment]
I thought about this some more - I think this feature somewhat goes against what TabFloater is supposed to be used for. Furthermore, implementation seems pretty complex, if even possible, and I have very little free time. So I'm closing this for now - if there is strong demand from other users, I will reconsider.

Thanks for the idea though!

**Comment by kostasvl** [comment]
Of course! Thanks for considering it! :)
