### ISSUE TITLE
Add the unfoat tab button on a floating window

### ISSUE THREAD

**Issue by the-phuctran** [tabfloater/tabfloater#262]
I know we can set a shortcut key for this but as a non-shortcut key user, is it possible to put a button for a fast click?

**Comment by ba32107** [comment]
Hi @the-phuctran,

You can use the same button to unfloat as the one you used to float:
![image](https://user-images.githubusercontent.com/26036493/135208532-6cdd0f54-640d-4f20-8c9e-0f6d448688a4.png)

Doesn't that work for you?

**Comment by the-phuctran** [comment]
OMG thank you I finally realize that way.
