### ISSUE TITLE
not working on youtube tab

### ISSUE THREAD

**Issue by dayumi13** [tabfloater/tabfloater#263]
## Description
[NOTE]: # ( Describe the problem below. What are you doing when the problem occurs? What would you expect to happen? What actually happens? )

## Reproduction steps
[NOTE]: # ( Provide an exact set of steps to reproduce this issue. Please be as detailed as you can. )
[NOTE]: # ( Start each step with "1." as you see below, it will be rendered as a numbered list. )
[TIP]:     # ( Provide a screenshot if you can. You can paste an image into this text box. )
 1. Step 1
 1. Step 2
 1. ....

## Environment
[NOTE]: # ( Provide information about your machine and environment. )
[NOTE]: # ( For "Companion installation", specify how you installed the Companion. E.g. for Windows: installer/portable, for Linux: AppImage/PPA )
 * **TabFloater version:** 
 * **Companion version:** 
 * **Operating system:**
 * **Browser**: 
 * **Companion installation:**

**Comment by ba32107** [comment]
Hi,

It does work for me. Please fill out the issue template and describe the problem properly.

Thanks

**Comment by ba32107** [comment]
Hmm I suspect the issue is with the special characters in the youtube video's title. But I just tried it and it does work for me. If you can reliably reproduce it, please let me know the steps and I can take a look.

thanks
