### ISSUE TITLE
Doesn't work in incognito

### ISSUE THREAD

**Issue by scdev0** [tabfloater/tabfloater#276]
## Description
[NOTE]: # ( Describe the problem below. What are you doing when the problem occurs? What would you expect to happen? What actually happens? )
- tabfloater doesn't work in incognito mode
- pressing Alt+K in incognito only moves the focus to a different tab without floating the selected tab

## Reproduction steps
[NOTE]: # ( Provide an exact set of steps to reproduce this issue. Please be as detailed as you can. )
[NOTE]: # ( Start each step with "1." as you see below, it will be rendered as a numbered list. )
[TIP]:     # ( Provide a screenshot if you can. You can paste an image into this text box. )
 1. Enable tabfloater to be used in incognito mode
 2. Open a tab in incognito mode
 3. Press Alt+K

## Environment
[NOTE]: # ( Provide information about your machine and environment. )
[NOTE]: # ( For "Companion installation", specify how you installed the Companion. E.g. for Windows: installer/portable, for Linux: AppImage/PPA )
 * **TabFloater version:** 1.22
 * **Companion version:** 1.22
 * **Operating system:** Windows 10
 * **Browser**: Chrome
 * **Companion installation (e.g. installed/portable, PPA/AppImage, etc):** installed

**Comment by ba32107** [comment]
Hi @scdev0, I was able to reproduce this - I've opened https://github.com/tabfloater/tabfloater/pull/277 to fix it.

**Comment by scdev0** [comment]
Thanks for the quick fix @ba32107 !

**Comment by scdev0** [comment]
Any idea when this would be released?

**Comment by ba32107** [comment]
Hi @scdev0, I do not maintain this project anymore - @JusstewaSNSJ would be able to release this
